version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_password}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-appdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  # 例: 将来的に Flask アプリを追加する場合は下記サービスをコメント解除
  # app:
  #   build: .
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - backend
  #   ports:
  #     - "8501:8501"

volumes:
  postgres-data:
    driver: local

networks:
  backend:
    driver: bridge
